### ISSUE TITLE
RerunOf configuration property should be used only if Rerun property is set to true

### ISSUE THREAD

**Issue by glibas** [reportportal/commons-net#102]
**Current behavior:** 

With parameters below launch **is reported as rerun**.

rp_launch_rerun=**false**
rp_launch_rerunof=some value

**Expected behavior:** 

With parameters below **new launch created**

rp_launch_rerun=**false**
rp_launch_rerunof=some value

The change is required to align with the behavior of the rest of the clients e.g. client-java

The following change required:
https://github.com/reportportal/commons-net/blob/8ead01bd0ba1d123dabd6787892a168395a8e80b/src/ReportPortal.Shared/Reporter/LaunchReporter.cs#L108

needs to be amended to check is rerun is set to true
`if (_rerunOfUuid != null && _isRerun)`

**Comment by nvborisenko** [comment]
Look reasonable, thanks.
