### ISSUE TITLE
Impossible upload log4net log file at end of tests execution

### ISSUE THREAD

**Issue by goblinmaks** [reportportal/commons-net#144]
Impossible to upload log4net log file from test solution in case if method 
`Context.Launch.Log.Info("Tests.log", new FileInfo(logFile));`

executes in [AfterTestRun] Specflow hook or [[OneTimeTearDown]](https://docs.nunit.org/articles/nunit/writing-tests/attributes/onetimeteardown.html) method. 

![image](https://github.com/reportportal/commons-net/assets/1436234/bbef6dba-6fcd-45de-bd45-9fe670750a1a)

Reason of this error in method GetLogMessageWithAttachmentFromFileInfo that used File.ReadAllBytes(file.FullName) that throw exception when tried to read file that used by another process.

**Comment by nvborisenko** [comment]
@goblinmaks can you please verify the code from PR on your end? I mean whether you can read file bytes.

**Comment by nvborisenko** [comment]
Released patch v3.6.1
