### ISSUE TITLE
Use some other keyword to merge configuration variables

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/commons-net#16]
Currently we use `+=` keyword to highlight that value should be concatenated with already registered.

This keyword blocks possibility to use it in command line provider.
We cannot write it:
```
Key1=+=Value1
```

**Comment by nvborisenko** [comment]
@aliaksandrbasau are you OK with `++`?

**Comment by nvborisenko** [comment]
I edited my comment above. Please review :)

**Comment by aliaksandrbasau** [comment]
@nvborisenko Would `Key1="+=Value1"` work for command line?

**Comment by nvborisenko** [comment]
No :( I am in context of `vstest`.
There we write like:
```cmd
dotnet test "-logger:ReportPortal;launch.name=asd qwe"
```

**Comment by aliaksandrbasau** [comment]
@nvborisenko I still think that it should be possible somehow. E.g.:
`dotnet test "-logger:ReportPortal;launch.name=asd qwe;launch.name=\"+=asd qwe\""`
or
`dotnet test '-logger:ReportPortal;launch.name=asd qwe;launch.name="+=asd qwe"'`

**Comment by nvborisenko** [comment]
Mm, verified both you ways, no successful. And don't forget about unix.

In case case the provided method should be very simple for user. I propose use `+` symbol in variables, it doesn't require to put additional symbols in cmd.

**Comment by nvborisenko** [comment]
Doesn't matter.
```cmd
dotnet test --logger:ReportPortal;launch.name="+asd asd"
``` works.

But
```cmd
dotnet test --logger:ReportPortal;launch.name="+=asd asd"
```
doesn't work.
> The Test Logger URI 'ReportPortal;launch.name=+=asd asd' is not valid.  The Test Logger will be ignored.

It's not only OS cmd paramereters parser. It seems `=` symbol is reserved.

**Comment by aliaksandrbasau** [comment]
@nvborisenko okay. But I still think that it should be possible to escape "=" somehow (unless vstest has a bug when parsing logger configuration).

**Comment by nvborisenko** [comment]
It needs deeper evaluation.

**Comment by nvborisenko** [comment]
Asked at https://github.com/Microsoft/vstest/issues/1889

**Comment by nvborisenko** [comment]
Yes, this is issue on vstest side.

2 options:
- wait until it will be fixed (not optimistic)
- use some other keyword

**Comment by aliaksandrbasau** [comment]
@nvborisenko Let's go with the second option even though there will be some inconsistency with the environment variable provider.

**Comment by nvborisenko** [comment]
Choosing between `+` and `++`. Any preferences?

**Comment by aliaksandrbasau** [comment]
I prefer `+` but `++` is a safer choice. Let's go with it.

**Comment by nvborisenko** [comment]
Thanks for your opinion. Will try to use `++`.
