### ISSUE TITLE
Introduce common internal logging mechanism

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/commons-net#2]
Goal:
Internally see what is going on and what is wrong. 

Requirements:
- No 3-party dependencies
- Shared on all levels (agent, bridge, client)
- Crossplatform
- Easy turn on or off

**Comment by nvborisenko** [comment]
Will not fix, agent and tests might live in different processes. So the logger should live on agent side.

**Comment by nvborisenko** [comment]
Reopening it since internal logging is supported by `netstandard2.0` via System.Diagnostics namespace. No 3rd party dependencies.

Due to different configuration options via agents we can use our own shared `IConfiguration` object to manage tracing mechanism.

**Comment by vitali-sonchyk-epam** [comment]
https://github.com/reportportal/commons-net/pull/30
