### ISSUE TITLE
Make the name of config json file case insensitive

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/commons-net#28]
It is already case insensitive on Windows, but not in Linux.

https://github.com/reportportal/commons-net/blob/d887d59eb13d22bd2c119fb3919be956dd4c1d45/src/ReportPortal.Shared/Configuration/Providers/JsonFileConfigurationProvider.cs#L27

We can blame this line of code.

**Comment by vitali-sonchyk-epam** [comment]
@nvborisenko 
Seems like on Linux and Windows OS there are differences in sensitivity of file names.
https://stackoverflow.com/questions/26300902/are-file-names-in-ubuntu-case-sensitive

File.txt & file.txt are the same files on Windows
and they are different instances on Linux.

We can create  custom case-insensitive verification like:
var allFiles = Directory.GetFiles(direcory);
if(allFiles.Any(x =>x.Equals(_filePath, StringComparison.OrdinalIgnoreCase ))
{
   // code
}

**Comment by nvborisenko** [comment]
Right. And we need not to forget about msbuild task which copies this file to output.

https://github.com/reportportal/commons-net/blob/master/src/ReportPortal.Shared.targets#L12

**Comment by vitali-sonchyk-epam** [comment]
@nvborisenko 
I didn't find a way to do it via MSBuild and asked a question on stackoverflow
https://stackoverflow.com/questions/58079857/msbuild-exist-condition-for-linux-ubuntu-case-sensitive-file-systems

Nott sure that the task is a correct one. Our consumer should understand the principle of file system work.

**Comment by nvborisenko** [comment]
We can test it manually. Just create a new project with installed nuget package and execute `dotnet build` on linux system.

**Comment by nvborisenko** [comment]
Interesting issue with msbuild target: I have `reportportal.config.json` file in the test project, and see `ReportPortal.config.json` in output (up-case). Windows OS.

**Comment by vitali-sonchyk-epam** [comment]
> Interesting issue with msbuild target: I have `reportportal.config.json` file in the test project, and see `ReportPortal.config.json` in output (up-case). Windows OS.

Seems like it is as expected according the:
https://github.com/reportportal/commons-net/blob/22b244ec75c88c8896b5c8a46930f6869d0bb797/src/ReportPortal.Shared.targets#L14

**Comment by nvborisenko** [comment]
It's a bug - msbuild task should not rename user's file (json config).
