### ISSUE TITLE
Log.Message is not working

### ISSUE THREAD

**Issue by Yaroshvitaliy** [reportportal/commons-net#36]
I am using NReportPortal.Shared NuGet v2.4.7 in my .Net application (F#).
`testItem.Log` works well:

             
```
let testItem = _launchReporter.StartChildTestReporter(startTestItemRequest)
logs |> Seq.iter testItem.Log
testItem.Finish(finishTestItemRequest)
```

But `Log.Message` is not working:

```
let testItem = _launchReporter.StartChildTestReporter(startTestItemRequest)
logs |> Seq.iter Log.Message
testItem.Finish(finishTestItemRequest)
```

I need make this working because I am going to use ReportPortal.Serilog sink that uses `Log.Message`.
According to documentation logs will be viewable under current test item from shared context, but I cannot see them.
Could you help me?

**Comment by nvborisenko** [comment]
Yes, what unit framework do you use? Recently the mechanism has been changed and now unit framework is responsible to handle all incoming log messages properly.

**Comment by Yaroshvitaliy** [comment]
I am using self-written unit framework that writes logs using Serilog and I need see them in ReportPortal

**Comment by nvborisenko** [comment]
Ok. in this case you should implement `ILogHandler` interface somewhere in your code. The name of `dll` file should start with `ReportPortal` (ReportPortal.*.dll sorry for that) and should be located near with "ReportPortal.Shared.dll" file. And your implementation will add log message to correct test item as you did it before.

Actually this is not very easy question. It's time to think about "extensibility points".

**Comment by Yaroshvitaliy** [comment]
Thank you. I'll try. Yes, I have been thinking about writing my own Serilog sink but the problem is that my application is not a part of a unit framework (let's say, extension for it) and  that's not so easy to get current testItem.

**Comment by nvborisenko** [comment]
This is purpose of `ILogHandler`. You says how to handle incoming log messages and assign it to proper `Test` (ITestReporter).

More over you are the the first guy who is writing extension, and extension on F#. There are many questions to resolve. Hopefully I can help.

**Comment by Yaroshvitaliy** [comment]
Thank you very much for your quick reply! I'll try to use `ILogHandler` and will answer.

**Comment by nvborisenko** [comment]
If you use the latest ReportPortal.Shared package, you can set up `ReportPortal_TraceLevel=Verbose` environment variable. It allows to see internal communication between dlls, in ReportPortal.*.log files. Might be usefull.

**Comment by Yaroshvitaliy** [comment]
@nvborisenko My project (dll) name is ....Sinks.ReportPortal so `ILogHandler` won't be working in my class and I need to create another project with name ReportPortal.*. It's not convenient for me.
What do you think about replacing in Bridge
```
AppDomain.CurrentDomain.GetAssemblies()
.Where(a => a.GetName().Name.StartsWith("ReportPortal"))
```
with
```
AppDomain.CurrentDomain.GetAssemblies()
.Where(a => a.GetName().Name.Contains("ReportPortal"))
```
So that any dll that contains `ReportPortal` in its name will be analyzed for extensions?

**Comment by nvborisenko** [comment]
I don't mind. Initially limitation was introduced due performance of types exploring https://github.com/reportportal/commons-net/issues/20

New `Contains()` limitation will be in the next package release.

**Comment by nvborisenko** [comment]
Available in v2.4.8.

@Yaroshvitaliy please try.

**Comment by Yaroshvitaliy** [comment]
Thank you! 
With v2.4.8 `Log.Message` is working in my app:

```
type MyLogHandler () =
    member val CurrentTestReporter: ITestReporter option = None with get, set
    
    interface ILogHandler with
        member x.Order =
            0
        
        member x.Handle(logRequest: AddLogItemRequest) =
            match x.CurrentTestReporter with
                | Some testReporter ->
                    testReporter.Log(logRequest)
                    true
                | None ->
                    false
```
Somewhere in my app:
```
                _testItem <-_launchReporter.StartChildTestReporter(startTestItemRequest)
                
                Bridge.LogHandlerExtensions
                |> Seq.filter (fun x -> x :? NBomberLogHandler)
                |> Seq.map (fun x -> x :?> NBomberLogHandler)
                |> Seq.iter (fun x -> x.CurrentTestReporter <- Some _testItem)
```
But ReportPortal Serilog sink still not working.

**Comment by nvborisenko** [comment]
@Yaroshvitaliy ReportPortal.Serilog sink uses `Log.Message()` inside. Just try to use `Log.Message()` method explicitly in your test to verify whether there are no issues with Serilog.

**Comment by Yaroshvitaliy** [comment]
@nvborisenko  Yes, that's definitely framework's logger configuration problem.
My problem is solved with implementation `ILogHandler` using package v2.4.8.
Thank you!
