### ISSUE TITLE
v5: Design of structured logging

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/commons-net#39]
In RPv5 there is possibility to report "nested log messages" aka "nested steps".

For BDD frameworks it will be built-in feature, they will report steps of scenarios as "nested steps" by default.

What if user can specify nested logging as well?.. Now we have `Log.Info(...)` methods which directly push messages to the server.

The first think is:
```csharp
using(var scope = Log.Scope("my logical piece of code"))
{
  ...
  scope.Info("my message");
  scope.Info("other message");
  Log.Info("hm, where am I from?") // not clear how to understand a parent of this message, does belong to root test?
  ...
}
```

**Comment by nvborisenko** [comment]
The hardest part is to understand it's scoped log in terms of RP or it's just a test item. I cannot imagine why test has inner tests... For BDD - yes, this is steps. The question is in terminology.

**Comment by nvborisenko** [comment]
Continuing to think:
```csharp
[Test]
public (void)/(async Task) Test1()
{
  Log.Info("message"); // it always goes to root test, asks ILogHandler extension to direct message to test
  using (ILogScope scope = Log.StartScope("logical piece of code")) // initiates creation of nested step, again asks ILogHandler extension per test framework (need adopt ILogHandler interface to support it)
  {
    Log.Info(""); // it always goes to root test
    scope.Info(""); // it goes to the scoped logging (aka nested step)

    Log.Active.Info(""); // it goes to the latest active scope based on context (AsyncLocal<T> should help us to resolve context). All log frameworks will use this entry point, so calling logFramework.Info("") should put messages to the active scope

    using (var scope2 = scope.StartNew("inner logical piece of code"))
    {
      // repeat

      Parallel.For(0, 3, () => Log.Active.Info("")); // should resolve scope2 as active scope (if possible)
      new Thread(() => Log.Active.Info("")).Start().Wait(); // should resolve scope2 as active scope (if possible)

      await Task.Delay();
      Log.Active.Info(""); // should resolve Active as scope2 for async/await programming model (where threads are mixing, again AsyncLocal<T> should help)
    }
  } // finishes scope
}
```

Impacts:
- Context resolving: if we cannot resolve active logging scope, everything should goes to root test. We loose structured logging, but it's better than loosing report.
- LogScope should be finished/disposed in any case to avoid breaking of reporting (when we don't finish some nested step on the server). Just use `using` statement in c#, in other cases this is responsibility of user to properly dispose LogScope.
- Seems AsyncLocal<T> is good candidate for resolving execution context flow, usage it requires net4.6+, we will drop supporting net4.5 (it's OK for me, 4.5 was released in 2012)

**Comment by nvborisenko** [comment]
Current implementation in `develop` branch:
```csharp
[Test]
public async/void Test1()
{
  Log.Info("");
  using (var scope = Log.BeginNewScope("a"))
  {
    Log.Info(""); // belongs to scope
    scope.Info(""); // belongs to scope
    Log.ActiveScope.Info(""); // belongs to scope (default entry point for any log framework appender)
    any_log_framewok.Info(""); // belongs to scope
    Log.RootScope.Info(""); // belongs to Test1

    using (var scope2 = Log.BeginNewScope("a")) // the same as scope.BeginNewScope("a")
    {
      // everything belongs to scope2, excepting Log.RootScope.Info("")
      DoSomeWork();
    }
  }
}

void DoSomeWork()
{
  // everything here should belong to scope where it's invoked from
  Log.Info();
}
```

- Supports multi-threading
- Even .NetFramework 4.5 (might face issues, mostly depends on unit framework who is aware about `CallContext`)
- Friendly to async/await

**Comment by madhukeshava** [comment]
is it the possible same way in python

**Comment by DzmitryHumianiuk** [comment]
@madhukeshava yes it is.
it just requires implementation.

we have group of contributors who is actively work on python client.
so it should be done in a while
