### ISSUE TITLE
Design api for communication between test assembly and agent

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/commons-net#46]
There is no easy way to influence on reporting from test assembly, because of agent and test live in different app domains/processes. This is why methods, as `Log.Info()`, delegate execution to extensions, which come from agent and agent knows how to process this command.

We need extend/rework api and cover more scenarios:
- Log messages to launch
- Amend current test item such as adding attributes, setting name/description
- Amend current launch item

**Comment by winstondz** [comment]
Maybe I am missing something , but I tried to add the attributes for saucelabs id using
 private void ReportPortalListener_BeforeTestFinished(object sender, TestItemFinishedEventArgs e)
        {
            var sessionIDProperty = TestExecutionContext.CurrentContext.CurrentTest.Properties.Get("SauceLabsSessionId");
            if (sessionIDProperty != null)
            {
                ItemAttribute attribute = new ItemAttribute()
                {
                    Key = "SLID",
                    Value = sessionIDProperty.ToString()
                };
                e.FinishTestItemRequest.Attributes.Add(attribute);
                attribute = new ItemAttribute()
                {
                    Key = "SLDC",
                    Value = "US"
                };
                e.FinishTestItemRequest.Attributes.Add(attribute);
            }                        
        }
But it does not work. I am using v4.0.0-beta3 of ReportPortal.NUnit . Is this how you envisioned the attributes to be used?

**Comment by nvborisenko** [comment]
This issue is about providing simple unified way to add attributes from your test.

```csharp
[Test]
public void YourTest()
{
  ReportPortal.Shared.Context.Test.AddAttribute(...);
}
```

In your code, I guess, `TestExecutionContext.CurrentContext.CurrentTest` is incorrect object and doesn't represent current test because code is executing in different process. I think your approach will work if you execute tests with `--inprocess` command line argument.

**Comment by winstondz** [comment]
I tried adding a generic attribute key value using (SLDC , US) using the above approach without the if condition inside the FinishTestItemRequest and it does not work too.  I based it on this customization file : https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

Do I need to update anything ? I am using Report Portal - [Current version:API Service: 5.2.1;Index Service: 5.0.7;Authorization Service: 5.2.1;Service UI: 5.2.0] and 
![image](https://user-images.githubusercontent.com/27180604/85733636-f5fa8200-b6c1-11ea-825b-a74ea809f79a.png)

**Comment by winstondz** [comment]
Nvm..I think there is some issue with the customization file. I had to downgrade nunit engine to 3.10 and it broke something in there.

**Comment by winstondz** [comment]
Quick question : Does the attributes functionality inside customization file require nunit engine 3.11.1 . When I run with 3.10 , i dont see it being added?

**Comment by winstondz** [comment]
ok. I resolved the nunit dependency, but unable to add attributes using the samples in customization. Should I move this to a separate issue?

        private void ReportPortalListener_BeforeRunStarted(object sender, RunStartedEventArgs e)
        {
            // add custom attributes
            e.StartLaunchRequest.Attributes.Add(new ItemAttribute { Value = "test_tag" });           
        }

        private void ReportPortalListener_AfterTestStarted(object sender, TestItemStartedEventArgs e)
        {
            e.StartTestItemRequest.Attributes.Add(new ItemAttribute { Value = "test_tag" });
        }

**Comment by nvborisenko** [comment]
@winstondz yes, please post a separate issue in https://github.com/reportportal/agent-net-nunit repository.

**Comment by winstondz** [comment]
Alright moved this issue to https://github.com/reportportal/agent-net-nunit/issues/63

**Comment by nvborisenko** [comment]
@winstondz done for nunit as beta `ReportPortal.NUnit v4.0.0-beta.4`
Example: https://github.com/reportportal/example-net-nunit/blob/488c6ca35c7e4dfa6d4933f59062e79e86f720b0/src/Example/Tests/Class1.cs#L143
