### ISSUE TITLE
How do I add attributes to report portal config using env variables instead of json file? 

### ISSUE THREAD

**Issue by winstondz** [reportportal/commons-net#49]
Is there an example I can refer to? Is there a way to add multiple key value pairs in different env variables due to size limitations.
I am able to add the other parameters following the guidelines at https://github.com/reportportal/commons-net/blob/master/docs/Configuration.md

But for attributes , I am running into System.Net.Http.HttpRequestException: Response message: {"errorCode":4001,"message":"Incorrect Request. [Field 'attributes[].value' should have size from '1' to '128'.] "}
  
I am able to add one or two attributes, but I encounter the issue when I try to add more
 ReportPortal_launch_attributes= string value of attribute array (key:value)

**Comment by nvborisenko** [comment]
Works for me:
```cmd
set reportportal_launch_attributes=key1:value1;key2:value2;
```

On RP:
![image](https://user-images.githubusercontent.com/22616990/88320601-7c889a80-cd26-11ea-8f14-fc1df2188a78.png)

Or appending env attributes to json attributes using `++` prefix:
```cmd
set reportportal_launch_attributes=++key1:value1;key2:value2;
```

Regarding attributes size limitation: seems you are trying to send long attribute value. For now please avoid it, posted issue https://github.com/reportportal/client-net/issues/57

Regarding specification of attributes in different env variables: it's good idea, but hard to implement. Need think about it. In any way this is big change, and don't expect it implemented soon.

**Comment by winstondz** [comment]
ok. I was dynamically creating the json file using jenkins. But wanted to see if I could use env variables instead, so that I can change these more easily then writing to the json file inside jenkins pipeline. For now, let me keep using the json file.

**Comment by nvborisenko** [comment]
Reopening. Which case is blocking you to use env variables?

**Comment by winstondz** [comment]
Its actually related to the size limitation issue which you already opened. Since I have a bunch of attributes which cannot be serialized into string inside an env variable within 128:
 reportPortalParameters.attributeTags = [
                                "TestType:${testParameters.testType}",
                                "JenkinsUser:${buildUser}", 
                                "JenkinsBuildNumber:${buildNumber}", 
                                "TestStack:${testParameters.executionHost}", 
                                "JenkinsNode:${env.NODE_NAME}",
                                "ApplicationBuildVersion:version"

These go over the size limitation. So I will just follow the other issue (#57) and for now just add these attributes by creating a new json config dynamically in the app build location.  You can close this issue if needed

**Comment by nvborisenko** [comment]
In your case only one attribute exceeds limitation. I'm wondering which one. There is no difference in json config source and env variables source. I can imagine that your attribute value may contain `:` or `;`. These symbols are reserved and used as items separators.

Is it possible to see the exact env variable value?

In case my assumption is true, we should rethink/rework strategy of specifying enumerable configuration values.
