### ISSUE TITLE
Preserve log messages order

### ISSUE THREAD

**Issue by sbakharev** [reportportal/commons-net#6]
Most of the operations by RP .NET client/shared libraries are performed asynchronously with several basic `Wait()`s assuring that already started critical tasks will be finished before the dependent tasks would start execution. _In fact_ this asynchronicity causes a whole set of problems when making custom RP integration using abovementioned libraries if you want your integration to be "bulletproof" against a variety of possible exceptional situations (**especially** when used in multithreaded context).

But if most of possible problems (which usually emerge as 406 Not Acceptable) come out of programming errors (not finishing items, finishing them in the wrong order, starting items within already finished items etc), there is at least one issue which seems like it shall be handled by the `TestReporter` class itself.

Imagine two (or more) log messages being posted shortly one after another, shortly enough for their effective timestamps to equal. Such coincidences are absolutely normal and even expected since RP uses timestamps with millisecond precision. As a result the order of such log messages within the test item is indeterminate - there is no guarantee which request would be delivered to and then processed by the server faster. And when messages within a log are unordered, this of course can no longer be considered a normal log.

When tests are run in parallel and their resultant order within a test suite is indeterminate - that's OK, but _log messages_ **must** be sequential.

We are testing web services. So the operations within tests are very fast. And I had to implement several pretty nasty constructions in my RP integration classes to make sure the logs don't get messed up.

Please fix this. And **thank you a lot** for what you do! RP is awesome :)

**Comment by nvborisenko** [comment]
@sbakharev, the ordering of log messages is fixed in code. Let us know whether you are waiting new version of nuget package.

**Comment by nvborisenko** [comment]
Should be resolved in scope of #5
