### ISSUE TITLE
BeginScope seems to cause the Server to get hung up

### ISSUE THREAD

**Issue by GeraldWood** [reportportal/commons-net#63]
I am new to this and I must be something wrong in what I am doing..but...

I just add this one line

Scope = Log.BeginScope(m_TestStepName);

The Test finishes but the Server seems to get hung up when taking the results in.

**Comment by nvborisenko** [comment]
@GeraldWood seems you are doing right. Please share more code around this problematic line.

> Server seems to get hung up

How does it look like?

**Comment by GeraldWood** [comment]
My code....
   [TestFixture]
    public class ReportPortalScopeTest
    {
        [Test]
        public void TestScope()
        {
            var scope = Log.BeginScope($"Scope 1");
            scope.Info($"Scope 1 Log Info");

            var scope2 = Log.BeginScope("Scope Level 2");
            Log.Debug("Level 2 message");

            scope2.Status = LogScopeStatus.Failed;
        }
    }

**Comment by nvborisenko** [comment]
You missed ending of log scope which is implemented as `Dispose()`. So just call `.Dispose()` method when scope should be finilized.

Recommended usage is
```csharp
using (var s = Context.Current.Log.BeginScope("")) // this begins scope, it's in progress state not
{
  // your code here
} // this implicitly ends scope (Dispose) even if your code raises an exception
```

**Comment by GeraldWood** [comment]
Thanks...I figured that out as well
