### ISSUE TITLE
[FEATURE] Ability do not send some attachment types to RP after test is completed

### ISSUE THREAD

**Issue by Shakevg** [reportportal/commons-net#68]
Sometimes we have big attachments generated during the test run and it requires a lot of space to store them on RP.
But we have a local copy or copy on CI tool (like Azure DevOps) of such attachment.
It will be great to have the ability to exclude some attachment extensions that send to RP in the RP configuration file.

**Comment by nvborisenko** [comment]
Should be resolved by #72 

Then it will be easy to manage logs reporting on your side via custom extension (cancelling, modifying, etc). Will try to support.

**Comment by Aleh-Yanushkevich** [comment]
@Shakevg as was montioned by @nvborisenko, now it's possible to manage logs reporting by implementation custom extension. In your case you have to implement [ICommandsListener](https://github.com/reportportal/commons-net/blob/develop/src/ReportPortal.Shared/Extensibility/ICommandsListener.cs) interface. Class which implements this interface should be in library, which con
tains **ReportPortal**  in assembly name. If it is not library with your tests, then just add the library as a reference to project with your tests. 
Here you can find example of ignoring attachements on log message.
[RPObserverExample.zip](https://github.com/reportportal/commons-net/files/9128235/RPObserverExample.zip)

@nvborisenko I would suggest to update documentation by adding examples of using custom extensions.

**Comment by nvborisenko** [comment]
Good hack, but the log message will come to RP without binary. Here we want to cancel sending this log item at all to the RP.

**Comment by Aleh-Yanushkevich** [comment]
> Good hack, but the log message will come to RP without binary. Here we want to cancel sending this log item at all to the RP.

sure.

**Comment by Shakevg** [comment]
I want to specify in the RP config file list of ext that should not be sent to RP

**Comment by nvborisenko** [comment]
Ok, good feature for https://github.com/nvborisenko/reportportal-extensions-skippable extension, the nature of functionality is similar. @Aleh-Yanushkevich I will apreciate to see you as contributor there.

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko I'll do it.

**Comment by nvborisenko** [comment]
@Shakevg new version of https://github.com/nvborisenko/reportportal-extensions-skippable is released with supporting of skipping log attachments. Check it out.
